## Generated SDC file "ALU_N2.out.sdc"

## Copyright (C) 2018  Intel Corporation. All rights reserved.
## Your use of Intel Corporation's design tools, logic functions 
## and other software and tools, and its AMPP partner logic 
## functions, and any output files from any of the foregoing 
## (including device programming or simulation files), and any 
## associated documentation or information are expressly subject 
## to the terms and conditions of the Intel Program License 
## Subscription Agreement, the Intel Quartus Prime License Agreement,
## the Intel FPGA IP License Agreement, or other applicable license
## agreement, including, without limitation, that your use is for
## the sole purpose of programming logic devices manufactured by
## Intel and sold by Intel or its authorized distributors.  Please
## refer to the applicable agreement for further details.


## VENDOR  "Altera"
## PROGRAM "Quartus Prime"
## VERSION "Version 18.0.0 Build 614 04/24/2018 SJ Lite Edition"

## DATE    "Fri Aug 31 19:24:05 2018"

##
## DEVICE  "5CSEMA5F31C6"
##


#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3



#**************************************************************
# Create Clock
#**************************************************************

create_clock -name {clk} -period 10.000 -waveform { 0.000 5.000 } [get_ports {clk}]


#**************************************************************
# Create Generated Clock
#**************************************************************



#**************************************************************
# Set Clock Latency
#**************************************************************



#**************************************************************
# Set Clock Uncertainty
#**************************************************************

set_clock_uncertainty -rise_from [get_clocks {clk}] -rise_to [get_clocks {clk}] -setup 0.160  
set_clock_uncertainty -rise_from [get_clocks {clk}] -fall_to [get_clocks {clk}] -setup 0.160  
set_clock_uncertainty -fall_from [get_clocks {clk}] -rise_to [get_clocks {clk}] -setup 0.160  
set_clock_uncertainty -fall_from [get_clocks {clk}] -fall_to [get_clocks {clk}] -setup 0.160  


#**************************************************************
# Set Input Delay
#**************************************************************

set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[0]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[1]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[2]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[3]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[4]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[5]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[6]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[7]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[8]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[9]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[10]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[11]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[12]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[13]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[14]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[15]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[16]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[17]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[18]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[19]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[20]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[21]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[22]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[23]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[24]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[25]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[26]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[27]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[28]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[29]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[30]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[31]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[32]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[33]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[34]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[35]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[36]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[37]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[38]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[39]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[40]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[41]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[42]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[43]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[44]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[45]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[46]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[47]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[48]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[49]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[50]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[51]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[52]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[53]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[54]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[55]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[56]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[57]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[58]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[59]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[60]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[61]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[62]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[63]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[64]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[65]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[66]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[67]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[68]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[69]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[70]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[71]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[72]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[73]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[74]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[75]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[76]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[77]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[78]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[79]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[80]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[81]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[82]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[83]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[84]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[85]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[86]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[87]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[88]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[89]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[90]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[91]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[92]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[93]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[94]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[95]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[96]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[97]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[98]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[99]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[100]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[101]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[102]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[103]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[104]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[105]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[106]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[107]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[108]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[109]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[110]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[111]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[112]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[113]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[114]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[115]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[116]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[117]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[118]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[119]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[120]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[121]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[122]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[123]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[124]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[125]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[126]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[127]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[128]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[129]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[130]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[131]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[132]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[133]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[134]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[135]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[136]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[137]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[138]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[139]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[140]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[141]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[142]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[143]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[144]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[145]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[146]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[147]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[148]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[149]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[150]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[151]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[152]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[153]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[154]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[155]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[156]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[157]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[158]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[159]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[160]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[161]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[162]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[163]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[164]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[165]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[166]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[167]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[168]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[169]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[170]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[171]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[172]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[173]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[174]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[175]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[176]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[177]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[178]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[179]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[180]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[181]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[182]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[183]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[184]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[185]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[186]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[187]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[188]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[189]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[190]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[191]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[192]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[193]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[194]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[195]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[196]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[197]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[198]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[199]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[200]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[201]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[202]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[203]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[204]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[205]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[206]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[207]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[208]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[209]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[210]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[211]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[212]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[213]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[214]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[215]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[216]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[217]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[218]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[219]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[220]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[221]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[222]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[223]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[224]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[225]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[226]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[227]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[228]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[229]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[230]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[231]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[232]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[233]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[234]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[235]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[236]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[237]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[238]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[239]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[240]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[241]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[242]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[243]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[244]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[245]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[246]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[247]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[248]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[249]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[250]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[251]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[252]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[253]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[254]}]
set_input_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {A[255]}]


#**************************************************************
# Set Output Delay
#**************************************************************

set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[0]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[1]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[2]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[3]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[4]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[5]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[6]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[7]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[8]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[9]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[10]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[11]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[12]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[13]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[14]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[15]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[16]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[17]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[18]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[19]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[20]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[21]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[22]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[23]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[24]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[25]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[26]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[27]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[28]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[29]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[30]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[31]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[32]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[33]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[34]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[35]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[36]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[37]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[38]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[39]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[40]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[41]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[42]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[43]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[44]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[45]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[46]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[47]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[48]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[49]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[50]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[51]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[52]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[53]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[54]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[55]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[56]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[57]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[58]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[59]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[60]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[61]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[62]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[63]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[64]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[65]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[66]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[67]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[68]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[69]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[70]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[71]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[72]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[73]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[74]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[75]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[76]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[77]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[78]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[79]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[80]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[81]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[82]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[83]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[84]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[85]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[86]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[87]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[88]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[89]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[90]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[91]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[92]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[93]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[94]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[95]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[96]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[97]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[98]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[99]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[100]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[101]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[102]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[103]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[104]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[105]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[106]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[107]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[108]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[109]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[110]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[111]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[112]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[113]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[114]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[115]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[116]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[117]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[118]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[119]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[120]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[121]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[122]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[123]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[124]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[125]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[126]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[127]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[128]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[129]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[130]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[131]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[132]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[133]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[134]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[135]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[136]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[137]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[138]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[139]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[140]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[141]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[142]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[143]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[144]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[145]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[146]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[147]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[148]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[149]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[150]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[151]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[152]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[153]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[154]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[155]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[156]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[157]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[158]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[159]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[160]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[161]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[162]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[163]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[164]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[165]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[166]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[167]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[168]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[169]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[170]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[171]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[172]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[173]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[174]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[175]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[176]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[177]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[178]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[179]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[180]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[181]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[182]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[183]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[184]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[185]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[186]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[187]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[188]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[189]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[190]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[191]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[192]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[193]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[194]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[195]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[196]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[197]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[198]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[199]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[200]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[201]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[202]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[203]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[204]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[205]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[206]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[207]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[208]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[209]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[210]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[211]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[212]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[213]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[214]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[215]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[216]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[217]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[218]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[219]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[220]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[221]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[222]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[223]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[224]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[225]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[226]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[227]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[228]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[229]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[230]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[231]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[232]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[233]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[234]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[235]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[236]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[237]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[238]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[239]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[240]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[241]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[242]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[243]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[244]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[245]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[246]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[247]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[248]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[249]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[250]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[251]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[252]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[253]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[254]}]
set_output_delay -add_delay  -clock [get_clocks {clk}]  2.000 [get_ports {Y[255]}]


#**************************************************************
# Set Clock Groups
#**************************************************************



#**************************************************************
# Set False Path
#**************************************************************



#**************************************************************
# Set Multicycle Path
#**************************************************************



#**************************************************************
# Set Maximum Delay
#**************************************************************



#**************************************************************
# Set Minimum Delay
#**************************************************************



#**************************************************************
# Set Input Transition
#**************************************************************

